schema_tms010 = {
    'UPD_DATE':('DATE', 'REQUIRED'),
    'IDNO':('INT64', 'NULLABLE'),
    'MKD':('DATETIME', 'NULLABLE'),
    'UPD':('DATETIME', 'NULLABLE'),
    'MSDT':('DATE', 'NULLABLE'),
    'MSID':('INT64', 'NULLABLE'),
    'JKBN':('INT64', 'NULLABLE'),
    'PLANNG':('STRING', 'NULLABLE'),
    'JCONTENTS':('STRING', 'NULLABLE'),
    'RANK':('INT64', 'NULLABLE'),
    'DELF':('INT64', 'NULLABLE')
}

schema_vma0060={
    'DT':('DATE', 'REQUIRED'),
    'EMP_CD':('INTEGER', 'NULLABLE'),
    'S_CD1':('INTEGER', 'NULLABLE'),
    'S_NM1':('STRING', 'NULLABLE'),
    'POSTCD':('INTEGER', 'NULLABLE'),
    'POSTNM':('STRING', 'NULLABLE'),
    'POST_RANK':('INTEGER', 'NULLABLE'),
    'POST_RANKNM':('STRING', 'NULLABLE'),
    'BUMON_CD':('INTEGER', 'NULLABLE'),
    'BU_CD':('INTEGER', 'NULLABLE'),
    'LEDKBN':('FLOAT64', 'NULLABLE'),
    'EGYKBN':('FLOAT64', 'NULLABLE'),
    'STAFF_FLG':('FLOAT64', 'NULLABLE'),
    'BUMON_NM':('STRING', 'NULLABLE'),
    'GET_LCD':('INTEGER', 'NULLABLE')
}

schema_tms060 = {
    'UPD_DATE':('DATE', 'REQUIRED'),
    'SUID':('INT64', 'NULLABLE'),
    'IDNO':('INT64', 'NULLABLE'),
    'MSID':('INT64', 'NULLABLE'),
    'MSDT':('DATE', 'NULLABLE'),
    'REF_DF':('DATETIME', 'NULLABLE'),
    'REF_DL':('DATETIME', 'NULLABLE'),
    'MK_FLG':('INT64', 'NULLABLE'),
    'SV_FLG':('INT64', 'NULLABLE'),
    'POINT':('INT64', 'NULLABLE'),
    'POINT2':('INT64', 'NULLABLE'),
    'POINT3':('INT64', 'NULLABLE')

}