name: Deploy to Cloud Functions

on:
  push:
    branches:
      - develop
      - main

env:
  PROJECT_ID: ifind-dm
  REGION: us-central1
  SOURCE_DIR: src

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ env.SOURCE_DIR }}/requirements.txt

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Set environment-specific variables
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "FUNCTION_NAME=dev--import-icj-data-function" >> $GITHUB_ENV
          echo "BUCKET_NAME=iris-icj-data" >> $GITHUB_ENV
          echo "BQ_DATASET_ID=testtest" >> $GITHUB_ENV
          echo "TABLE_PREFIX=dev_" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "ENVIRONMENT=prd" >> $GITHUB_ENV
          echo "FUNCTION_NAME=prd-import-icj-data-function" >> $GITHUB_ENV
          echo "BUCKET_NAME=iris-icj-data" >> $GITHUB_ENV
          echo "BQ_DATASET_ID=iris_lv0_ic_journal_iadb_iris" >> $GITHUB_ENV
          echo "TABLE_PREFIX=prd_" >> $GITHUB_ENV
        fi

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --region=${{ env.REGION }} \
          --source=${{ env.SOURCE_DIR }} \
          --trigger-bucket=${{ env.BUCKET_NAME }} \
          --runtime=python39 \
          --entry-point=main \
          --set-env-vars=ENVIRONMENT=${{ env.ENVIRONMENT }},PROJECT_ID=${{ env.PROJECT_ID }},BQ_DATASET_ID=${{ env.BQ_DATASET_ID }},TABLE_PREFIX=${{ env.TABLE_PREFIX }}