name: Deploy to Cloud Functions

on:
  push:
    branches:
      - develop
      - main

env:
  PROJECT_ID: ifind-dm
  REGION: us-central1
  SOURCE_DIR: src
  PROJECT_NUMBER: '614186555151'
  POOL_ID: github-actions-pool
  PROVIDER_ID: github
  SERVICE_ACCOUNT: ifind-dm-developers@ifind-dm.iam.gserviceaccount.com
  PUBSUB_TOPIC: storage-events-icj-data

jobs:
  deploy:
    # リポジトリが ifind-dm 組織に属していることを確認
    if: github.repository_owner == 'ifind-dm'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.POOL_ID }}/providers/${{ env.PROVIDER_ID }}'
        service_account: ${{ env.SERVICE_ACCOUNT }}

    - name: Set environment-specific variables
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "FUNCTION_NAME=dev-import-icj-data-function" >> $GITHUB_ENV
          echo "BUCKET_NAME=iris-icj-data" >> $GITHUB_ENV
          echo "BQ_DATASET_ID=testtest" >> $GITHUB_ENV
          echo "TABLE_PREFIX=dev_" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "ENVIRONMENT=prd" >> $GITHUB_ENV
          echo "FUNCTION_NAME=prd-import-icj-data-function" >> $GITHUB_ENV
          echo "BUCKET_NAME=iris-icj-data" >> $GITHUB_ENV
          echo "BQ_DATASET_ID=iris_lv0_ic_journal_iadb_iris" >> $GITHUB_ENV
          echo "TABLE_PREFIX=prd_" >> $GITHUB_ENV
        fi

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --region=${{ env.REGION }} \
          --source=${{ env.SOURCE_DIR }} \
          --trigger-topic=${{ env.PUBSUB_TOPIC }} \
          --runtime=python39 \
          --entry-point=main \
          --set-env-vars=ENVIRONMENT=${{ env.ENVIRONMENT }},PROJECT_ID=${{ env.PROJECT_ID }},BQ_DATASET_ID=${{ env.BQ_DATASET_ID }},TABLE_PREFIX=${{ env.TABLE_PREFIX }}